version: '3'
services:
  traefik:
    image: traefik:latest
    command: --docker --docker.domain=DOMAIN.duckdns.org
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    labels:
      - "traefik.frontend.rule=Host:traefik.DOMAIN.duckdns.org"
      - "traefik.port=8080"
    container_name: traefik
    restart: always

  pihole:
    container_name: pihole

    image: pihole/pihole:latest
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 8054:80/tcp
      - 444:443
    volumes:
    # run touch ./pihole.log first unless you like errors
    #  - ./pihole.log:/var/log/pihole.log
      - /docker/pihole/:/etc/pihole/

    environment:
      ServerIP: IP-OPI
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: DOMAIN.duckdns.org
      VIRTUAL_PORT: 80
      TZ: 'Europe/Madrid'
      WEBPASSWORD: 'PASSWORD'
      DNSMASQ_LISTENING: all
    restart: unless-stopped
    networks:
      - traefik
    labels:
       # required when using --docker.exposedbydefault=false
       - "traefik.enable=true"
       # https://www.techjunktrunk.com/docker/2017/11/03/traefik-default-server-catch-all/
       - "traefik.frontend.rule=HostRegexp:pihole.DOMAIN.duckdns.org,{catchall:.*}"
       - "traefik.frontend.priority=1"
       - "traefik.backend=pihole"
       - "traefik.port=80"

networks:
  traefik:
    external: true
